version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "step-functions-fizzbuzz"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-s35lgwuzh65a"
s3_prefix = "step-functions-fizzbuzz"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
